server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_notes?useSSL=false
    username: xxx
    password: xxx
   
  jpa:
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL8Dialect # For MySQL 8
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
